version: '3.8'

services:
  apigateway:
    container_name: apigateway
    build:
      context: ..  
      dockerfile: src/ApiGateway/Dockerfile
    image: apigateway
    ports:
      - "8000:8080"
    depends_on:
      - eventservice
      - identityservice
    networks:
      - backend

  identityservice:
    container_name: identityservice
    build:
      context: ..  
      dockerfile: src/Services/IdentityService/Identity.Api/Dockerfile
    image: identityservice
    ports:
      - "8002:8080"
    networks:
      - backend

  eventservice:
    container_name: eventservice
    build:
      context: .. 
      dockerfile: src/Services/EventService/Event.Api/Dockerfile
    image: eventservice
    ports:
      - "8001:8080"
    networks:
      - backend

  registrationservice:
    container_name: registrationservice
    build:
      context: ..  
      dockerfile: src/Services/RegistrationService/Registration.Api/Dockerfile
    image: registrationservice
    ports:
      - "8003:8080"
    networks:
      - backend

  notificationservice:
    container_name: notificationservice
    build:
      context: ..  
      dockerfile: src/Services/NotificationService/Notification.Api/Dockerfile
    image: notificationservice
    ports:
      - "8004:8080"
    networks:
      - backend

  analyticsservice:
    container_name: analyticsservice
    build:
      context: .. 
      dockerfile: src/Services/AnalyticsService/Analytics.Api/Dockerfile
    image: analyticsservice
    ports:
      - "8005:8080"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge