name: Verify PR Build

on:
  pull_request:
    branches:
      - main  # Runs only for PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore EventAggregatorPlatform.sln

      - name: Build Solution
        run: dotnet build EventAggregatorPlatform.sln --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test EventAggregatorPlatform.sln --configuration Release --no-build --verbosity normal
